* new notes/log
** 1/7- 2/7

- sdr tuning doesn't seem to match or pick up radio transmission // also how to tune across or do interesting stuff with this?

- trimmer across coil works fine...

- use HIH 4030 for humidity rather than DHT 22 (temp and humidity there but seems quite static)

https://learn.sparkfun.com/tutorials/hih-4030-humidity-sensor-hookup-guide?_ga=2.135316018.2085594342.1530547889-891593741.1493728855

- 4093 theremin for HF maybe/stripped down for FM section

TODO: 

test levels into FM transmitter

HIH6131-021-001 Honeywell Board Mount Humidity Sensors (mouser) to test - 3.3V!

+MAX2606 transmitter tests, but we need inductor SMD also? 390 nH? - can we tune with voltage (maybe leave 2606)!+

74xx/4093 transmission sections also

** 4/7

- add lowpass -68R->signal in ->

                              |
                            100N
                              |
                              VGND


- wormedvoice pwm output as model (just make upload from makefile to flash to arduino there/at least in code)

- 7404 transmission works: http://www.rf-kits.com/schematics/SimpleFmTransmitter.pdf

- ADD optional pre-emphasis and de-emphasis??? passive

https://ham.stackexchange.com/questions/9163/pre-emphasis-measurement

http://www.techlib.com/area_50/Readers/Karen/radio.htm

- i2c grove receiver:

working with GROVE: library at: https://github.com/mathertel/Radio/

can only tune across so fast and then is always tuning jump

we use debugscan and lowest delay there is (300)

see also https://github.com/lucsmall/Arduino-RDA5807M/blob/master/A20150415RDA5807FMTuner.ino

- think about using AC/555 into mushroom and measure this using atmega instead of bridge?

http://www.emesystems.com/OLDSITE/OL2mhos.htm

and then count pulses - so on atmega input should be ??? also maybe raw 555 signal

i don;t think we need pullup

INT0 is PD2

- discard MEMS

- HIH6131 in: https://github.com/benwis/SparkFun-Kicad-Libraries - uses MOSI?SCK and not ADC

ref also: https://hackaday.io/project/2117/logs?sort=oldest

- P-MOSFET? smd - SOT23 or SOT223 ??? SI2309, NXP2301P-reichelt (GSD) - we use this?

- added xtal for 16MHZ?

** 5/7 +

- test RF amp
- test pre-emph and transmitter
- test 555 thing
- possible two transistor transmitter

- checking schematic:

*** micro:

checked as is microSD which differs from SD, we need to add temp SPI: ADDED - hardware spi with CS on pin PB1

- where is the microsd code we use always for atmega skrying?

=  /root/projects/archived/bordeaux/new_skry

in sd_raw stuff there we have SS pin configured

*** sensor: 

check HIH6131 SS? - check if is spi or i2c? we have 6131-021 which is i2c - software i2c so... changed to use just SDA and SCL

ref: https://playground.arduino.cc/Main/HoneywellHumidIconTMDigitalHumidity-TemperatureSensors

- AD5933 we used ages ago could be interesting?

*** rf board

- checked PMOS FET

** 6/7

re-check all schematics and DRC and re-check connections which look wired in but prompt DRC

- tested pre-emph working and op07 rf amp working... (maybe larger amp there)

- no to ad620 but maybe use ad5933 as potential breakout (5v and SDA/SCL) - i2c comms only ADDED to breakout

(for that breakout add op-amps for vin and vout as in eval board, plus precision 3v as in last design/walker)


* receivers// with arduino/pi

** GRV I2C FM Arduino - Grove I2C FM Receiver - reichelt

based on RDA5807M. 

arduino: http://wiki.seeedstudio.com/Grove-I2C_FM_Receiver/

RDA5807xx chip is a clone of the TEA5767

https://www.element14.com/community/blogs/sasg/2014/01/19/controlling-the-rda5807sp-fm-radio-receiver-with-the-raspberry-pi

http://www.raspberry-pi-geek.com/Archive/2016/16/Remote-controlled-Arduino-FM-radio

- SI4825-A10-CS Silicon Labs RF Receiver - mouser 

see https://www.mouser.de/datasheet/2/368/Si4825-A10-276730.pdf and used in KOMA:

https://koma-elektronik.com/new/wp-content/uploads/2017/07/KOMA-Elektronik-FieldKit-PR1-Schematics.pdf

but question of i2c also

* design notes

- pcb thickness 1.2mm

* TODO: 

- test import svg in pcbnew: this works following: https://andrehessling.de/2016/09/13/getting-a-custom-board-outline-from-an-svg-file-into-kicad/

: pstoedit -dt -f "dxf:-polyaslines -mm" myc_outline3.eps myc_outline3.dxf

- how we connect power and signals between boards - sketch this out

say power/gnd/3.3v/audio1/audio2/ so 5 lines across lower part of each module to be connected

POWER/GND/audio-micro_in/micro audio out/.../pwm with jumper also

... but for micro we also need to break out/across with CLK, SDO, SDI, CS = SPI

and for humidity = ADC or I2C or SPI? ADC

5v connection in...

- different signals: micro-output pwm, input sample/or straight eg. mems micro etc ...
- what are the possible signals
- changing transmission capacitance
- connections to mycelium - also in base
- any special footprints - for sensors
- basic schematic

* what sensors/other devices/electronics we will use?

opamp from microcontroller...

combine some of these and use jumpers or different ADC sample options

1- for temperature we use breakout: MAX31865 - 8 pin break 5V 

2- MEMs mic: kicad footprints for INMP504 -3.3v/reflow, HLGA packagings
 
NMP504ACEZ-R7 TDK MEMS Microphones - mouser

3- humidity: moisture/resistance - in the air, 4-in the mushroom (resistance bridge/ADC)?

5 humidity: SHT15-pricey, SI7021-DFN/cheap,
HIH6130-soic/medium**ORDERED-6131, BME280-tricky/medium, - these ones
also do temp/what accuracy?  HIH4030-5v/easy/medium/ADC

6- RF retransmission = antenna amp as in detektor -> ADC (so is not floating)

7- theremin like oscillator: http://www.instructables.com/id/Make-Your-Own-Simple-Theremin/ 4093/op-amp

http://interface.khm.de/index.php/lab/interfaces-advanced/theremin-as-a-capacitive-sensing-device/

8- light/spectrometer (light source/detector) - offboard for insertion into mushroom - photodiode(voltage?) and white LED?

as well as basic disruptors//timed signal disrupters/FET - modulated by mushroom itself

live coding of signals as code

* transmitter

- breakout for changing capacitance
- audio in
- wire wound coil!
- switch on and off with FET?

2n2222A -SMD**ORDERED // BC546B // BC547

* generic micro/sd board

sd card holder footprint/order - which one we used as pcb footprint - check!

WURTH 693072010801 

* performance

Radio Mycelium workshop and opening performance:

Seventeen participants will form an inter-species, human-mycelial
radio performance network, activating the molecular Mycelium Network
Society installation and instantiating an active mycelial/mushroom
audio networked circuit.

Within the mushroom molecule structure seventeen transmission devices
are pre-installed which operate according to local mycelial conditions
and transmit small-scale material change information across wide-band
radio frequencies. These devices will interface with local humidity,
temperature and radio signals within the growing mycelial bodies,
sometimes creating rich signals, sometimes blocking or jamming signals
within a very close space, parasitically riding on local space
electromagnetic emissions.

Prior to the performance, seventeen sound artists will take part in an
open workshop building DIY radio receivers and sculptural antennae,
testing the reception of signals and interfacing with open examples of
the Lingzhi growing mushroom. Throughout the workshop a fungal
dramaturgy will be developed for the opening performance, comprising
acts which are dominated by certain received sets of signals.

During the performance, the seventeen artists will work with spatially
defined radio signals, and moving radio receivers within the
constraints of an eight channel sound system which allows for precise
localisation of sound signals. Artists will also play with their own
approaches to handheld Lingzhi fungi which will serve as audio and
full spectrum instruments. The performance is a collaboration between
electronic sensibilities and the extra human realms of radio frequency
and Lingzhi.

* tech needs

tech needs:

For installation:

Seventeen sensor/transmitter/jammers will be installed - one in each
of the atoms forming the molecule. These devices (custom made
electronics and circuit boards) will examine small-scale material
changes within the mycelial atoms and transmit this information across
wide-band radio frequencies, for later audio spatialisation as part of
the installation. 

8x FM radio receivers/receiver modules in the space 

8x mid-range active monitors (Genelec 8040)

PC and 12 channel soundcard (RME Hammerfall)

Eight channel analogue audio mixer


For performance:

Opening performance will re-work the transmissions from the
molecule/17 transmission devices within the space by 17 local sound
artists.

32 channel analogue audio mixer

17x FM radio receivers

PA - 2xsubs and 4x mid-range D&B or L.Acoustics with all cables
