* pins

ADC/AVR/micro pins down from top= 1-5v, 2-GND, 3-mush=1, 4-spare=2, 5-light=0, 6-co2=3,7-SCL, 8-SDA, 9-+3.3V

earthboot pins: from underneath left: 5v for 5933, 3,3V, GND, 620_OUT, SCL, SDA

range of both 04 and transistor is full FM 87-107 MHz

POWER: +V *AT_TOP* (and now protection diode to put in!), white stripe is GND on all cables

* TODO and type of mycel radio modules

** TODO

- how to work with SD and not just as AFSK - despite slow speed of SD read/write:

loop through and change livecode, voice params//other data sends

also new kansas and softmodem code in arduino dir to test with SD DONE!

(also AFSK = 1200 bps bits per second /8 = 150 bytes per sec = potential for 150 reads = 0.006 secs max for read = 6mS)

- test all performance modules, all have long power cablesX, power for
  all and add leg points, make legs (more brass + also flexi-copper
  legs)

test 555->micro audio codes - noise or clicks?

arduino test case: myc_arduino - just uploads via makefile/plain c - tested wormed!

- scheme for FET: record value, when we reach abs DEVIATION do something (FET or pulse/click) and record new value...

clean up code for 4 variations and also FET codings...

- continuous AFSK...
- intermittent - clicks also - pulses - myc.c rough versions
- very intermittent - noise or other bursts
- disturbers - low level, capacitance, rf and audio through mushrooms, mushroom antennas, white noise, mush caps...

*check ADC read as 10 bit seems best - fix ADLAR options as in arduino/livecode example*

- new FET code - find lowest and highest or max difference

- plan for workshop and performance
- test all radio receivers, pair power supply, *own radio/arduino done (x2)* so total 8 receivers
- waterproofing

** done

+wormed voice with ADC2 as mode select and freeze DONE in arduino test folder+

+build, test - 4 or 5 microsXDONE, 1 04DONE, 5 transistorDONE - all sensor/psu/fet/theremin DONE 2/10 // 9/10+

+test micros so far-FUSES programmed, add power diode, add cables and fit together, re-program and test+

+[RF signals through mushrooms], test capacitanceX+

+TESTED all analogue modules+

+test sd card read and write/afsk codeDONE+

+ORDER+DONE: extra 4.5v AAA (x3) holders for performanceX+

+twisted wireX, 4mm circle at end-how thick?-use resistor wire, blocking diode (1n5819)X, mega8X,  check all partsX, connectorsX, psu for radios-checkX, bolt 4mm for wires testX+

** modules for linz workshop/labelled - see list also in diary below

1- temp-micro-sd-tran-FET ->2
2- op07-micro-tran - FET ->14
3- 4093-nomicro-04 ->13
4- 555-nomicro-04 ->11
5- ad620-micro-tran-FET ->6
6- humidity-tran SD ->1
7- humidity/HIH/555/sd-tran-FET ->4

now re-labelled as:

** List modules - all built - see myc_modules_list.org

// more with replacement caps, more theremin, antenna into mushroom, audio into mushroom, 

FET switchings based on say mushroom adc ...

transistor transmit with:

1-micro/HIH-humidity SDcard-built X 
2-micro/MAX-temperature SDcard- X

3-micro/CO2 SDcard 
4-micro/555 in X +HIH humidity X
5-micro/ADC mushroom in
6-micro/earthboot620in X

04 transmit with:

7-micro/HIH-humidity SDCard-
8-micro/MAX-temperature SDcard
9-micro/ADC mushroom in
10-555->transistor - micro gated?
11-555->04 X
12-theremin->transistor - micro gated?
13-theremin->04 - X
14-OP07->transistor (micro gated) X

15-OP07->04 (no 3.3v, no micro) 

16-transmitter with 555/micro source and replacement caps1 - micro gated?
17-transmitter with 555/micro source and replacement caps2 - micro gated?

how many MCP602=20-3(built)=18 

*** to make for performance DONE

- no FET, no waterproofings-18+! 4.5V

LIST 8: 18/19/20/21/22/23/24/25/

18- ADC1 in + added ADC2 for mode- - micro trans -X
19- earthboot/620 in -micro tran s
20/21- 555 raw transmit x2 -04
22- replacement caps with op07 into trans no 3.3V 
23- replacement caps with ADC in need micro trans
24/25- theremin x2 04 no 3.3V

** basic test setup

- micro: sensor in, serial out, fet switching
- radio: power and signal in, radio tuned
- sensor: with micro or just signal out (op, 555)

** sound strategies...

- wormed voice to port...
- microbd/livecoding
- test tones/white noise filtered (check MOZZI), noise or tone bursts

+ strategies for FET timings... we can also modulate with turning FET
  on/off, value used to determine burst of transmission timing/gap

- white noise, wormed voice oscillations, shift register with leaks, test tone transmits - regularity driven

minimal, what makes most sense: bursts, silence also gated, not so loud transmissions

** moisture testing/sealing

epoxy, nail varnish, hot glue, dip in resin - silicone rubber type 16, crystal clear modulor...

** reading raw SD for checking

- once is taped in use myc_sdreader.c TEST!

** C02 sensor - what is kind of base line and range

range is maybe 0-60 for differences once has settled down

** older list

transmitters: transistor(switchable), HC04

with input to trans or HC04 from:

- micro with humidity, MAXtemp, CO2, 555 in, ADC mushroom, ADC from AD620 earthboot(TESTED), 5933 from earthboot (7 options)

- 555 out TESTED
- 4093/theremin out TESTED as audio and as transmit into 04
- OP07 RF out TESTED as audio

-HC04 transmitter lacking 33pf to test - tested with 22pf which puts it at top of FM which is good!

= 20 possibilities. for 17 say 14 micros and 3 analogues or more

and additional option to always just use micro to switch on/off transmitter either according to score or with environmental conditions

[no light option...]

* visual score to taipei

not all 17 have radios, some have mushrooms to manipulate (say 7 mushroom)

- bare radio, no amp, one person goes in circle with radio
- others join movement in space, only one radio, how movement effects micro radio space
- slowly others very low volume switch on radios (tuned already only to one spot which is free, never change tuning)
- return to start location and plug in, mixer down

- form groupd around mushroom setups

- first performer paired with mushroom person, slow manipulations amplified

- other join to new score:
-- mushroom words
-- mushroom voice
-- mushroom noise

others can join with radios, some move only in space and vocalise maybe low voices

dying down towards mushroom heat/smoke laser end...

unplug, reduce volume and all end by circling mushroom with radios (all now so 17)

* workshop plan taipei

- introduction and demonstrate slowly bit by bit
- each person tries with radio
- find pairs for mushroom/radio pair - no pairing now, what temporary stations can be formed and re-formed

- work through the visual score (printed)

** packing list

- psu for testing, all tools (cutters, iron, solder, multimeter, extra wire, extra copper, copper, wirings for all parts, spares, diodes)
- all radios and all psu, 2x arduino, cables, psu and radio receiver modules,
- for workshop: printouts, other circuits, extra batteries, radios to get there+open_call!


* workshop plan linz

http://stwst48x4.stwst.at/radio_mns_workshop  Mycelial Radio Activation

Sa, 8. Sept, 2018, 11:00 - 17:00
at STWST48x4, Linz, Austria

- first tea
- Intro to interspecies communications, project ideas, radio platform // reader re-launch
- show modules and designs

- building and interfacing to mushrooms - simple circuits, 04, theremin, transistor
- playing with this and further ideas - voice?
- reception/detection

- ideas for a score/translations
- tasting and burning/tea
- final micro ritual/performance

** materials/pack list

- detektorsx2X
- dried lingzhi for teaX
- copper wires 0.8mm and 1mmX
- arduino, cables and receiver moduleX
- audio cables/minijackX
- radio receiversX

- copper sheetsX, thin boardsX, copper sticky sheetsX, basic wireX, solderX, croc clipsX 
- parts box with op amps, resistors etc...X
- aaaX

*big and AA batteries for radios*

- tools-solder ironTHERE, multimeterX
- mycelium modules, sensors, *power supply* and breakout, programmer and cableX

- *candles for heating*

check parts:

thin copper boardsX, parts, several power supply 5v for arduino and modulesX 

- parts: battery clips-3xaaaX, 04: HC04 (note 5v only)x,XXalll parts 

check: 4.7KX, 47kx, 1kx, 2.5kx, 470Rx, 27Kx, 10KX, 15Kx

check: 33pfx2, 10pfx, 100pfx, 1Nx, 10ux

2.5k trimmerX???where?, re-ordered

04 transmits
theremin transmit: 4093x, 
transistor-based:2n2222x, 

wire 0.8, 1mmX

** tech rider

- tables, chairs, table lights, paper or whiteboard for diagrams,
  power strips offering say 10 outlets

- kettle, cups

- 8 channel analogue mixer, powered monitor speaker, 6x minijack to jack cables, 2x jack cables

- 6x good soldering irons with stands, 3 pairs scissors, 3 wire cutters, 1 pliers, 2x gluegun and gluesticks, 3x craft knives


* new notes/log
** 1/7- 2/7

- sdr tuning doesn't seem to match or pick up radio transmission // also how to tune across or do interesting stuff with this?

- trimmer across coil works fine...

- use HIH 4030 for humidity rather than DHT 22 (temp and humidity there but seems quite static)

https://learn.sparkfun.com/tutorials/hih-4030-humidity-sensor-hookup-guide?_ga=2.135316018.2085594342.1530547889-891593741.1493728855

- 4093 theremin for HF maybe/stripped down for FM section

TODO: 

test levels into FM transmitter

HIH6131-021-001 Honeywell Board Mount Humidity Sensors (mouser) to test - 3.3V!

+MAX2606 transmitter tests, but we need inductor SMD also? 390 nH? - can we tune with voltage (maybe leave 2606)!+

74xx/4093 transmission sections also

** 4/7

- add lowpass -68R->signal in ->

                              |
                            100N
                              |
                              VGND


- wormedvoice pwm output as model (just make upload from makefile to flash to arduino there/at least in code)

- 7404 transmission works: http://www.rf-kits.com/schematics/SimpleFmTransmitter.pdf

- ADD optional pre-emphasis and de-emphasis??? passive

https://ham.stackexchange.com/questions/9163/pre-emphasis-measurement

http://www.techlib.com/area_50/Readers/Karen/radio.htm

http://sound.whsites.net/project54.htm THIS ONE!

- i2c grove receiver:

working with GROVE: library at: https://github.com/mathertel/Radio/

can only tune across so fast and then is always tuning jump

we use debugscan and lowest delay there is (300)

see also https://github.com/lucsmall/Arduino-RDA5807M/blob/master/A20150415RDA5807FMTuner.ino

- think about using AC/555 into mushroom and measure this using atmega instead of bridge?

http://www.emesystems.com/OLDSITE/OL2mhos.htm

and then count pulses - so on atmega input should be ??? also maybe raw 555 signal

i don;t think we need pullup

INT0 is PD2

- discard MEMS

- HIH6131 in: https://github.com/benwis/SparkFun-Kicad-Libraries - uses MOSI?SCK and not ADC

ref also: https://hackaday.io/project/2117/logs?sort=oldest

- P-MOSFET? smd - SOT23 or SOT223 ??? SI2309, NXP2301P-reichelt (GSD) - we use this?

- added xtal for 16MHZ?

** 5/7 +

- test RF amp
- test pre-emph and transmitter
- test 555 thing
- possible two transistor transmitter

- checking schematic:

*** micro:

checked as is microSD which differs from SD, we need to add temp SPI: ADDED - hardware spi with CS on pin PB1

- where is the microsd code we use always for atmega skrying?

=  /root/projects/archived/bordeaux/new_skry

ref design is in Downloads

in sd_raw stuff there we have SS pin configured

*** sensor: 

check HIH6131 SS? - check if is spi or i2c? we have 6131-021 which is i2c - software i2c so... changed to use just SDA and SCL

ref: https://playground.arduino.cc/Main/HoneywellHumidIconTMDigitalHumidity-TemperatureSensors

- AD5933 we used ages ago could be interesting?

*** rf board

- checked PMOS FET (nxp2301= SOT23 (TO-236AB) )

** 6/7

re-check all schematics and DRC and re-check connections which look wired in but prompt DRC

- tested pre-emph working and op07 rf amp working... (maybe larger amp there)

- no to ad620 but maybe use ad5933 as potential breakout (5v and SDA/SCL) - i2c comms only ADDED to breakout

(for that breakout add op-amps for vin and vout as in eval board, plus precision 3v as in last design/walker)

** 10/7

- added 5v/Vcc and GND in to sensor board

re-checking 

- micro: fixed caps, fixed temp breakout, ss on micro-sd is fine, checked int0 for 555 pulse...

- fm: u3b is half of theremin, added incoming volume trimmer

- sensor: added pullup for 555

netlist:

Add trimmers and variable cap, *check sot23s and SO8N footprints...*

** 12/13//7

- Added trimmers and variable cap but we need to change for: http://cdn-reichelt.de/documents/datenblatt/B400/BI-SERIE-23.pdf - 23B!

DONE - checked all parts

- remember after we change cvpcb netlist to generate/save netlist in eeschema

- move power to sensor board as is too crowded and then re-check sizes? - we need to make biggerDONE

** 17/7

- working on pcb... fixed pins of SOT23 2n2222 on PCB, checked FET again, all checked. TODO: zones, vias and final parts check

- 5933 will need 3.3v supply (added - but ref needs 5v??) but not sure if we can sensibly decode on atmega in time...

- double up with new earthboot board with ad620 and 5933

- where was 5933 code? psyche.pde.bac

see also: https://github.com/mjmeli/arduino-ad5933

** 18/7

- for ad620/eeg and 5933 earthboot/myc board:

-- +no idea where+ eeg circuit is from but is simple ac coupled amp: Tom Collura's Brainmaster EEG schematics//20013608.txt

-- see also: https://www.instructables.com/id/Body-Composition-using-BIA/

** 19/7

- for earthboot board soldermask stuff - exported svg with triangle
  masks, into gimp (1000dpi) and overlaid prima materia circle and
  inverted it out (?), exported to tiff and import to layer/footprint
  with kicad bitmap tool.

** 20/7

- extended 5933 to 6.2mm (inside dimensions), for order ADR423 is
  SOIC8 so works out, and added jumper for 2v to ref of AD620 all on
  earthboot board (so can use ad620 with no filtering) - note that
  otherwise we are down to low freq response for earthboot so we have
  slow input

** 21/7

- added jumper on radio board so we can power without micro/fet control

- changed 7404 transmitter so that we can also jumper or control power from FET

** 23/7

- added zones and vias (split zone on earthboot board), checked, checked gerbers, re-check and order

- myc: all 1.2mm thick, 75x84mm
- earthboot: 1.2mm, 51x130mm

** 13/8

- boards arrived, test PSU-TESTED 

- test atmega8 programming/basic tones-DONE, with HIH-DONE, test
  transistor radio with fet switch and basic opsDONE, test sd card read/write

- programmed and flashed with usb hub and cable red to rightest part of adapter...

- we have to hack mosfet with additional 2n2222a and 2x 1k resistors
  (one across S and G, one to our switch signal) as in example
  circuit - pin 3 emitter to gate of NX2301, pin1 base 1k to switch,
  pin 3 to GND (wired)...

code is based on wormed voice//microBD

- MAX31865-SPI // adapt from adafruit library /// HIH moisture SPI too

so we need SPI functionality: http://www.tinkerer.eu/AVRLib/SPI/

HIH: https://github.com/ArsenioDev/HIH6131-SPI/blob/master/SPIHumidity2.ino

https://playground.arduino.cc/Main/HoneywellHumidIconTMDigitalHumidity-TemperatureSensors

what others: 5933, adc for CO2, for light, mushroom and maybe ad620 on board

and what generates pwm - wavetables, frequencies, reread SD, live codings...

SD read/write: code is: /root/projects/archived/bordeaux/new_skry

** 20/8

- where was 5933 code which was not for Arduino: main.c in /root/projects/archived/bordeaux/new_skry (along with SD code)

- for myc - tested serial fine, now HIH=i2c TODO-working

- SD card basic open/record - need to do playback - we could just use raw read/write access

at the moment with SDHC enabled we have size issues - fixed by removing FAT etc...

- MAX3xxx temp

- other sensors/AD5933

** 21/8

- MAX31865 code (simply ported from adafruit) is working - fixed so works with SD card... DONE
- 555 on INT0 countings DONE

////

- test other sensors/AD5933: CO2, ADC mushroom, ADC from AD620 earthboot(TEST), 5933 from earthboot

- test rest of hardware side of things:
- 555 out - TESTED 3.3V
- OP07 RF out - 5V - tested - leave off 10N - to test with radio transmitter!


- 4093/theremin out - all 5V - works as audio - TO TEST with transmission

- 4093 HF as standalone transmitter - doesn't do much and makes not so much sense...

- HC04 transmitter - *power jumper to note for only 04 and transistor NOT 4093!*


- waterproofing tests...

- ideas for score and programming

** 22/8

GRV I2C FM Arduino - Grove I2C FM Receiver - reichelt based on RDA5807M. 

voltage is either 3.3v or 5v test code for arduino in software based on: https://hackaday.io/project/9009-arduino-radio-with-rds

see also:

https://funprojects.blog/tag/rda5807/

http://cdn-reichelt.de/documents/datenblatt/A300/107020006_01.pdf

http://wiki.seeedstudio.com/Grove-I2C_FM_Receiver/

question of antenna?

** 30/8

numerous tests

- test change of sample rate to 16k

- assembled earthboot but not sure what RFB should be for incoming signal - 100K at moment.

TO TEST!

- experiments TODO: pass audio/pwm signals *through* mushroom, mushroom as FET switcher?

** 3/9

myc_wormedvoice.c:

// TODO: defines instead of switch, but maybe keep as switch so we can
// err switch with the mushroom, ranges of our adc and maybe working
// with differences

port in hardware stuff for now...

- how could we use say mushroom_adc(ADC1) for FET switching - running
  average and then switch/flipflop on deviation from that average
  exceeding/? done in some cases

- where is running average code? in wormed.c - test this out in myc_wormedvoice.c

** 4/9-5/9

idea of data radio style MSX or modem/AFSK/FSK/DTMF transmissions for data:

https://github.com/markqvist/MicroModem/blob/master/Modem/afsk.c

https://www.1010.co.uk/data_radio.html

https://chapmanworld.com/2015/04/07/arduino-uno-and-fast-pwm-for-afsk1200/

this one? https://github.com/DL1CB/ATMEGA8_Bell_AFSK_Generator/blob/master/ATMEGA8_Bell_AFSK_Generator.ino

PD3 OC2B is our PWM out!

based on this test_afsk is working

- max temp only works with SD card in holder

- tested all boards individually for workshop:

1- temp-micro-sd-tran-FETon/offtimer - AFSK - need to replace microDONE-Z

2- op07-micro-tran - FET -X - mushroom ADC controls FET /3rd pin down = ADC1 DONE-Z
3- 4093-nomicro-04 -X DONE-Z
4- 555-nomicro-04 -X DONE-Z

5- ad620-ADC2 micro-tran-FET - needs cable to earthboot-DONE - livecode -  livecode controls FET

-- all working!

extras from earlier

6- humidity -> tran FET - wormvoice TODO DONE-Z 
7- has humidity and 555 -> tran FET - AFSK TODO-> no fet action DONE-Z

** 5/9

Notes/TODO for next stage: 

- for humidity we need to see what approx levels and differences we have
- for co2 also

- how to work more with FET timings...
- use white noise filter also
- more control and passing signals through mushrooms

** 1/10

- myc_afsk_temp_sd.c is latest SD/AFSK looping to test with temperature

** 9/10

installation 17: 4 sets to program

- continuous AFSK...
- intermittent - clicks also - pulses - myc.c rough versions
- very intermittent - noise or other bursts
- disturbers - low level, capacitance, rf and audio through mushrooms, mushroom antennas, white noise, mush caps...

for perf modules with micro: different mushroom modes on one ADC!

** 23/10

- watch ports from arduino and always remember ot set sei()
- watch other files which get compiles - raw sd has large array

* receivers// with arduino/pi

** GRV I2C FM Arduino - Grove I2C FM Receiver - reichelt

based on RDA5807M. 

arduino: http://wiki.seeedstudio.com/Grove-I2C_FM_Receiver/

RDA5807xx chip is a clone of the TEA5767

https://www.element14.com/community/blogs/sasg/2014/01/19/controlling-the-rda5807sp-fm-radio-receiver-with-the-raspberry-pi

http://www.raspberry-pi-geek.com/Archive/2016/16/Remote-controlled-Arduino-FM-radio

voltage is either 3.3v or 5v

test code for arduino in software

- SI4825-A10-CS Silicon Labs RF Receiver - mouser 

see https://www.mouser.de/datasheet/2/368/Si4825-A10-276730.pdf and used in KOMA:

https://koma-elektronik.com/new/wp-content/uploads/2017/07/KOMA-Elektronik-FieldKit-PR1-Schematics.pdf

but question of i2c also

* design notes

- pcb thickness 1.2mm

* TODO/DONE: 

- test import svg in pcbnew: this works following: https://andrehessling.de/2016/09/13/getting-a-custom-board-outline-from-an-svg-file-into-kicad/

convert to eps in inkscape...

: pstoedit -dt -f "dxf:-polyaslines -mm" myc_outline3.eps myc_outline3.dxf

- how we connect power and signals between boards - sketch this out

say power/gnd/3.3v/audio1/audio2/ so 5 lines across lower part of each module to be connected

POWER/GND/audio-micro_in/micro audio out/.../pwm with jumper also

... but for micro we also need to break out/across with CLK, SDO, SDI, CS = SPI

and for humidity = ADC or I2C or SPI? ADC

5v connection in...

- different signals: micro-output pwm, input sample/or straight eg. mems micro etc ...
- what are the possible signals
- changing transmission capacitance
- connections to mycelium - also in base
- any special footprints - for sensors
- basic schematic

* what sensors/other devices/electronics we will use?

opamp from microcontroller...

combine some of these and use jumpers or different ADC sample options

1- for temperature we use breakout: MAX31865 - 8 pin break 5V 

+2- MEMs mic: kicad footprints for INMP504 -3.3v/reflow, HLGA packagings+
 
+NMP504ACEZ-R7 TDK MEMS Microphones - mouser+

3- humidity: moisture/resistance - in the air, 4-in the mushroom (resistance bridge/ADC)?

5 humidity: SHT15-pricey, SI7021-DFN/cheap,
HIH6130-soic/medium**ORDERED-6131, BME280-tricky/medium, - these ones
also do temp/what accuracy?  HIH4030-5v/easy/medium/ADC

6- RF retransmission = antenna amp as in detektor -> ADC (so is not floating)

7- theremin like oscillator: http://www.instructables.com/id/Make-Your-Own-Simple-Theremin/ 4093/op-amp

http://interface.khm.de/index.php/lab/interfaces-advanced/theremin-as-a-capacitive-sensing-device/

8- light/spectrometer (light source/detector) - offboard for insertion into mushroom - photodiode(voltage?) and white LED?

as well as basic disruptors//timed signal disrupters/FET - modulated by mushroom itself

live coding of signals as code

* transmitter

- breakout for changing capacitance
- audio in
- wire wound coil!
- switch on and off with FET?

2n2222A -SMD**ORDERED // BC546B // BC547

* generic micro/sd board

sd card holder footprint/order - which one we used as pcb footprint - check!

WURTH 693072010801 

* performance

Radio Mycelium workshop and opening performance:

Seventeen participants will form an inter-species, human-mycelial
radio performance network, activating the molecular Mycelium Network
Society installation and instantiating an active mycelial/mushroom
audio networked circuit.

Within the mushroom molecule structure seventeen transmission devices
are pre-installed which operate according to local mycelial conditions
and transmit small-scale material change information across wide-band
radio frequencies. These devices will interface with local humidity,
temperature and radio signals within the growing mycelial bodies,
sometimes creating rich signals, sometimes blocking or jamming signals
within a very close space, parasitically riding on local space
electromagnetic emissions.

Prior to the performance, seventeen sound artists will take part in an
open workshop building DIY radio receivers and sculptural antennae,
testing the reception of signals and interfacing with open examples of
the Lingzhi growing mushroom. Throughout the workshop a fungal
dramaturgy will be developed for the opening performance, comprising
acts which are dominated by certain received sets of signals.

During the performance, the seventeen artists will work with spatially
defined radio signals, and moving radio receivers within the
constraints of an eight channel sound system which allows for precise
localisation of sound signals. Artists will also play with their own
approaches to handheld Lingzhi fungi which will serve as audio and
full spectrum instruments. The performance is a collaboration between
electronic sensibilities and the extra human realms of radio frequency
and Lingzhi.

* tech needs

tech needs:

For installation:

Seventeen sensor/transmitter/jammers will be installed - one in each
of the atoms forming the molecule. These devices (custom made
electronics and circuit boards) will examine small-scale material
changes within the mycelial atoms and transmit this information across
wide-band radio frequencies, for later audio spatialisation as part of
the installation. 

8x FM radio receivers/receiver modules in the space 

8x mid-range active monitors (Genelec 8040)

PC and 12 channel soundcard (RME Hammerfall)

Eight channel analogue audio mixer


For performance:

Opening performance will re-work the transmissions from the
molecule/17 transmission devices within the space by 17 local sound
artists.

32 channel analogue audio mixer

17x FM radio receivers

PA - 2xsubs and 4x mid-range D&B or L.Acoustics with all cables
