* 17 for installation to specify - all built

- continuous
- intermittent or clicks
- very intermittent - burst of osc or noise
- disturbers - audio into mush, mush antennas, white noise, mushroom caps...

* softwares: 

- AFSK, softmodem, kansas, click transmit maybe - with SD!
- white noise and filter
- live coding = livecode2 -> we can also have adc for just plague or cpu
- wormed voice
- clicks
- oscillation pulses

* Transistor transmit with (check gating):

T-tested/done

1-micro/HIH-humidity SDcard-SOFT: SD, sounds good but not using SD? 

2-micro/MAX-temperature SDcard-SOFT: SD, *AFSK afsk_temp_sd gate on...* 

3-micro/CO2 SDcard -SOFT: SD, GATE, NOTE to put CO2 on ADC1!, *kansas. no gate NO VOL* 

4-micro/555 in +HIH humidity -SOFT: SD, *clicks transmit - run through sd bits as click, no click* clicks.c with gate on click, adc3 pulse length! 

5-micro/ADC mushroom in -SOFT: GATE, *gate in livecode. livecode ADC, cpu=9* 

6-micro/earthboot620in -SOFT: *wormed voice mode=14, FET on deviation NO VOL* 

* 04 transmit with:

7-micro/HIH-humidity SDCard-  -SOFT: SD, *softmodem with SD*  *FReq and vol fixed - NO TUNE**

8-micro/MAX-temperature -SOFT: *wormedvoice - mode on ADC3* 

9-micro/ADC mushroom in -SOFT: *livecode ADC1 cpu9 and plague1 - NO VOL* 

10-555->transistor - micro gated?  -SOFT: *gate on 555, 555 signal to micro for gating only* 

11-555->04 

* misc - disturbers

12-theremin->transistor - micro gated  -SOFT: *gating only - sequenced seconds+adc*  

13-theremin->04 

14-OP07->transistor (micro gated) -SOFT: *gating only - with ADC/scheme* 

15-OP07->04 (no 3.3v, no micro) 

////

16-transmitter with 555/micro source - trans and replacement caps1 - micro gated  -SOFT: *no gating, 555->micro, pwm, whitenoise filter NO VOL NO TUNE* 

17-transmitter with 555/micro source -trans and replacement caps2 - micro gated  -SOFT: *gating, 555->micro clicks with empty signal* 

SPARE- 04 transmit with micro and ADC1 - worm voice mode=3


* For performance 18-25

18- ADC1 in -micro trans -SOFT: *wormed voice with ADC1 as input and ADC2 as mode*  

19- earthboot/620 in - replacement 10P -micro trans  -SOFT: *live code with ADC2 as cpu/plague, ADC3 as input*  

20- 555 raw transmit -04 

21- 555 raw transmit -04 

22- replacement/parallel caps with op07 into trans no 3.3V 

23- replacement caps with ADC in micro trans  -SOFT: *live code with ADC1 as input and ADC0 as mode select 

24- theremin 04 no 3.3V 

25- theremin 04 no 3.3V 

